### ISSUE TITLE
什么是算法、数据结构，能用来做什么？

### ISSUE THREAD

**Issue by jingt06** [geekplux/programming-FAQ#4]
@geekplux

**Comment by allenfantasy** [comment]
Good question. 这里我尝试用自己的语言描述一下（尽量不引入新名词和概念）：

### 算法

首先这个概念并不局限于计算机，也可以应用到数学等其他学科。为了方便解释，这里的 "算法" 即等同于 **计算机算法**。算法的一些特征有：
- 解决某种问题所需要采用的方法步骤的统称
- 算法接受一些特定的输入，经过若干步骤得到一个输出（结果），视为算法完成
- 我们需要通过编写程序的方式，来控制计算机按照算法的步骤进行操作，并接受输入，输出结果

#### 1个栗子

比如说我们现在在北京的西直门，要找到去东单的最近的交通路线，那我们期望得到的结果是具体的一个出行计划（如：到X站坐53路车到Y，然后走500米到Z站坐地铁N号线）以及该计划需要的总时间。

为了得到这个结果，我们需要知道从西直门到东单之间的距离，所有可能的交通工具（地铁/公交/步行）的分布情况，以及这些交通工具的起止点和速度，如果要得到一个实时的结果我们还需要知道当前各个道路的通行状况的数据（车速）。

最后在得到这些数据之后，我们需要用一个机智的方法来计算出 **最优路线**，这个机智的方法就是所谓的算法。

#### 总结

输入数据 ==> 算法 ==> 实现算法的程序 ==> 输出结果

### 数据结构

在上述的 **求最佳路径** 的例子中，我们需要一些输入的数据，这些输入数据从结构上各有不同：
- 不同的交通工具（X条地铁线/Y条公交线）可以视作一个 **列表**
- 各个互相连通的道路的数据 可以视作一个 **图**
- 从一个点出发蔓延到其他点的路径可以视作一颗 **树**

这些 **列表**，**图** 和 **树** 就是承载数据的不同结构，在计算机科学中我们将其统称为 **数据结构**

### 二者关系

在算法中我们需要对各类数据进行处理，处理的过程中就不免要涉及操作各种不同的数据结构。

而这两者的结合就基本上构成了编写程序的最主要部分。

**Comment by geekplux** [comment]
@allenfantasy 回答的太好了
所以 @jingt06  是不是可以close了

**Comment by yorkie** [comment]
＋1
