### ISSUE TITLE
增加Vim的部分

### ISSUE THREAD

**Issue by yorkie** [geekplux/programming-FAQ#7]
由 @wsdjeg 提出：

> @yorkie 不建议罗列所有细则，建议以搭建一个vim环境 配合 相关tips 来处理，如果将vim所有基础内容都加进来，就没有什么吸引力了

**Comment by wsdjeg** [comment]
- [ ] vim 文件结构 
- [ ] 脚本读取顺序
- [ ] 插件管理
- [ ] 各种补全方式
- [ ] 常用插件

**Comment by yorkie** [comment]
> vim 文件结构

这个会不会对初学者有点生涩，作为初学者，我觉得最想知道的是怎么提高他写代码，查Bug的产能，而不是知道Vim是啥吧。

> 脚本读取顺序

同上一条

> 插件管理

这个赞

> 各种补全方式

文字中不要有“各种”这样泛指的修饰词，能否细化成有哪几种，不全之后再补也可以

> 常用插件

我觉得这个可以和第三个“插件管理”整理在一个小节中，顺序如下：
- 使用插件
- 插件管理
- 常用插件列表

Ok, 希望可以按照上面的方式整理，如果我有误读或者不同的意义，可以继续讨论在下。

> @wsdjeg Thanks for this awesome work :+1:

**Comment by wsdjeg** [comment]
这里有一个误区,目前我接触了很多刚开始使用vim的,都是在网上找了一个配置文件,直接复制过来使用,然后各种奇葩问题,对于vim的基本目录结构有一个大致的了解,更有利于理解为搭建最基本的vim环境.而且对于新手来说,更重要的是开始安装vim 以及 开始使用,至于如何使用,那是基于他已经能够成功安装vim并了解该如何修改配置文件,至于如何修改,那就需要对vimscript有一些深入学习了.

**Comment by geekplux** [comment]
@wsdjeg  首先感谢:)

如果关于「为什么要用 vim」也可以稍微阐述一下就更好了
入门方面（安装、搭建确实很重要）可以你自己写，也可以添加相关链接。

你觉得呢  👀

**Comment by wsdjeg** [comment]
不错的建议,近期打算开始整理了.

**Comment by geekplux** [comment]
@wsdjeg Nice, 我也可以再学习一遍。需要我把你拉进 org 吗？我给你开一个 vim 的 repo

**Comment by wsdjeg** [comment]
开一个VIDE REPO,毕竟我们不是要push vim ,而是基于vim vimscript 的环境搭建 及其使用

**Comment by geekplux** [comment]
@wsdjeg [vim repo](https://github.com/reflight/vim)

Thank you

**Comment by yorkie** [comment]
@geekplux Add him to collaborators list

**Comment by wsdjeg** [comment]
最好不要用vim作为仓库名,不过这并不影响我push

**Comment by geekplux** [comment]
@wsdjeg  any idea?

**Comment by wsdjeg** [comment]
VIDE vimmer-dotfiles 暂时还未想到,不过 还是需要看仓库的具体方向,是打算搭建环境,还是打算做教程,抑或是TIPS收藏
